node {

    def commit_id

    stage('Preparation') {

        checkout scm

        sh "git rev-parse --short HEAD" > .git/commit_id
        commit_id = readFile(.git/commit_id).trim()

    }

    stage('test') {

        nodejs(nodeJsInstalationName: 'nodejs') {
            sh 'npm install --only=dev'
            sh 'npm test'
        }
    }

    stage('docker build/push') {
        docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
            def app = docker.build("cinguilherme/node-docker:${commit_id}", '.').push()
        }
    }

}