node {

    def commit_id

    stage('Preparation') {

        checkout scm

        sh "git rev-parse --short HEAD > .git/commit_id"
        commit_id = readFile('.git/commit_id').trim()

    }

    stage('test') {

        nodejs(nodeJSInstallationName: 'nodejs') {
            sh 'npm install --only=dev'
            sh 'npm test'
        }
    }

    stage('docker build/push') {
        docker.withRegistry('https://dockerhub.com', 'dockerhub') {
            def app = docker.build("cinguilherme/node-docker:${commit_id}", '.').push()
        }
    }

}